### ISSUE TITLE
if there's no exact match in the database, try a fuzzy search

### ISSUE THREAD

**Issue by tmaybe** [codeforamerica/glossary-bot#11]

**Comment by tmaybe** [comment]
maybe respond privately with fuzzy matches so the person can choose whether to define a match publicly?

**Comment by migurski** [comment]
:+1: to private preview.

**Comment by mathowie** [comment]
I would like to see this feature as well.

**Comment by nmsonline** [comment]
I would LOVE this. Currently I'm just adding definitions for multiple terms (abbreviations and the like) instead of having a signposted redirection.
