### ISSUE TITLE
“shh” doesn’t work with term definitions

### ISSUE THREAD

**Issue by migurski** [codeforamerica/glossary-bot#19]
“Gloss Bot has set the definition for *shh TERM* to *DEFINITION*”

**Comment by tmaybe** [comment]
This is behaving as intended, but I'm open to a different behavior. Setting a definition doesn't generate a public response, therefore `shh` doesn't have any functional meaning in this context. So GB assumes you meant it as part of the term to be defined.

I think it'd be more frustrating If I auto-stripped `shh` and variants from the beginnings of definitions, which would make it impossible to add certain words and phrases to the glossary.

I could add a note at the end when I see someone using it this way? Like "*You don't need to use shh when you're setting definitions, Gloss Bot won't respond publicly.*"

**Comment by tmaybe** [comment]
Might do a similar not for `set` which is a no-longer used command.
