### ISSUE TITLE
Feature request: allow users to make an alias

### ISSUE THREAD

**Issue by mathowie** [codeforamerica/glossary-bot#24]
Sometimes a company can have three names to describe the identical feature or functionality in an application. It would be nice if I could make a definition for a phrase like "direct message" also correspond to the phrase "DM" in the glossary.

Currently, I just make a duplicate entry for both phrases, but I wish there was a command to keep track of only one definition I can update/delete later rather than maintain multiple copies of the definition under different terms.

**Comment by tmaybe** [comment]
I like this idea. I've had the same issue but hadn't conceptualized a solution that'd work like aliases.

What'd be a good way to structure the command for this? Something like:

`/gloss alias DM to Direct Message` or `/gloss alias DM = Direct Message`?

**Comment by mathowie** [comment]
Sorry I missed this response from you. Yeah, thinking more through this, it would be tough to come up with the syntax for aliasing, but also kinda tough to deal with deleting entries. If you delete the master entry, do all the aliases disappear too? But is deleting an alias ok?.

I like the /gloss alias DM = Direct Message best since it matches the adding a term syntax.

**Comment by tmaybe** [comment]
Good point. What if there was no primary entries, just a bunch of equal entries that shared a definition? Then when you deleted one, GB could tell you about the others, in case you wanted to go after them as well.
