### ISSUE TITLE
internal server error when trying to fetch

### ISSUE THREAD

**Issue by nmsonline** [codeforamerica/glossary-bot#34]
Definitions/stats/anything that requires fetching results in "Error: Internal Server Error" message

**Comment by tmaybe** [comment]
Hi @nmsonline sorry you're having a problem with the bot. A few questions:

1. I assume that Slack Bot is reporting that error message to you in Slack?
1. Does `/gloss help` work?
1. Did you set up your Gloss Bot with the Heroku button or did you use the command-line instructions? 
1. And did you just set it up recently?

Thanks!

**Comment by nmsonline** [comment]
Thanks for getting back to me.

1. Yep.
2. Yep.
3. Yep.
4. Yep!

**Comment by nmsonline** [comment]
Thanks for getting back to me.

1. Yep.
2. Yep.
3. Yep.
4. Yep!

**Comment by tmaybe** [comment]
Hmm...

1. If you go to the Heroku page for your bot, do you see a Postgres Add-on listed there? It'd look something like this:

    ![postgres-addon](https://cloud.githubusercontent.com/assets/546665/10112259/7964a6ac-638e-11e5-853c-4bf6aa0de0c0.png)

2. Click on that and look in the `Statistics` area at the bottom of the page. Do you see the following values there?

    ```
    Plan: Dev
    Status: Available
    Tables: 3
    ```

3. In the same area, how many `Rows` (if any) does it say its using? (i.e. `100/10000`)

**Comment by nmsonline** [comment]
Plan
Hobby-dev

Status
Available

Primary
Yes 

Connections
0/20

Data Size
6.5 MB

Tables
3

Rollback
Unsupported

Rows
0/10000 (In compliance)

**Comment by tmaybe** [comment]
Okay, thanks @nmsonline. I need to do a little digging to figure out the next step of diagnosis. If you're willing, you might try scrapping this installation of Gloss Bot and starting over – you'd just have to re-enter the Slack tokens in the Heroku setup form and the change the bot's URL on Slack.

**Comment by nmsonline** [comment]
Competely scrapped it (deleted integrations & heroku deployment) and started again - same errors. help works, undefined terms work, but everything else generates the same error :-(

**Comment by tmaybe** [comment]
Okay. I'll try a fresh install this weekend and double-check the process. Maybe something changed at Heroku or Slack that breaks my setup process. My apologies again for your troubles.

**Comment by tmaybe** [comment]
hey @nmsonline, I just went through the whole sequence several times and was able to set up new bots with no problems. Here's a video of me creating a new one from scratch:

https://youtu.be/X-NgTE1OlpM

Do you see anything in there that is missing from your process?

**Comment by nmsonline** [comment]
I've done this twice, no difference - still the same error - rooting around in Logs now!

**Comment by nmsonline** [comment]
I have no idea why this is happening :-1:

**Comment by tmaybe** [comment]
I guess the next step would be to start rooting around on the Heroku machine. How comfortable are you with working on the command-line? You can get the [Heroku Toolbelt here](https://toolbelt.heroku.com/) and once you've set it up, use it to log-in to or run commands on the machine that's running your Gloss Bot. If you're willing to do that, I can give you some things to check.

**Comment by nmsonline** [comment]
I'm happy with that - otherwise another test would be for me to PM you a
token and URL to see if your Heroku instance works.

**Comment by tmaybe** [comment]
@nmsonline I just followed you on twitter; DM me your token & URL there and I'll send you a URL to enter into your Slack's slash commands config.
