### ISSUE TITLE
Do something useful on `/gloss` with no command

### ISSUE THREAD

**Issue by ab** [codeforamerica/glossary-bot#43]
My first hunch upon hearing about `/gloss` is just to run it with no arguments. Ideally this would do something useful, like be an alias for `/gloss help`, perhaps?

**Comment by tmaybe** [comment]
Hi @ab! It should already be aliased to `/gloss help` ... what behavior are you seeing?

**Comment by tmaybe** [comment]
[Here's the code](https://github.com/codeforamerica/glossary-bot/blob/master/gloss/views.py#L411)

**Comment by ab** [comment]
I swear slackbot gave me some generic error saying "Something went wrong", but now I can't reproduce it.
